#encoding:utf-8
'''
paper.stauts原始值为0-6,现为*10值, 6改为100
'''
FW_PAPER_STATUS_INIT = 0
FW_PAPER_STATUS_WAIT_AUDIT_1 = 10
FW_PAPER_STATUS_WAIT_AUDIT_2 = 20
FW_PAPER_STATUS_WAIT_AUDIT_3 = 21
FW_PAPER_STATUS_WAIT_AUDIT_4 = 30
FW_PAPER_STATUS_WAIT_AUDIT_5 = 40
FW_PAPER_STATUS_WAIT_AUDIT_6 = 50
FH_PAPER_STATUS_INPUT = 60
FH_PAPER_STATUS_WAIT_AUDIT_1 = 70
FH_PAPER_STATUS_WAIT_AUDIT_2 = 80
PAPER_STATUS_FINISH = 100

from userpro.enums import *

STATUS_PERM_DICT = {
    FW_INPUT_PERMISSION:FW_PAPER_STATUS_INIT,
    FW_BEGIN_AUDIT_PERMISSION:FW_PAPER_STATUS_WAIT_AUDIT_1,
    FW_QC_AUDIT_PERMISSION:FW_PAPER_STATUS_WAIT_AUDIT_2,
    FW_QC_AUDIT_PERMISSION2:FW_PAPER_STATUS_WAIT_AUDIT_3,
    FW_AREA_AUDIT_PERMISSION:FW_PAPER_STATUS_WAIT_AUDIT_4,
    FW_AUDIT_PERMISSION:FW_PAPER_STATUS_WAIT_AUDIT_5,
    FW_END_AUDIT_PERMISSION:FW_PAPER_STATUS_WAIT_AUDIT_6,
    
    FH_INPUT_PERMISSION:FH_PAPER_STATUS_INPUT,
    FH_AUDIT_PERMISSION:FH_PAPER_STATUS_WAIT_AUDIT_1,
    FH_END_AUDIT_PERMISSION:FH_PAPER_STATUS_WAIT_AUDIT_2,
    MANAGER_PERMISSION:PAPER_STATUS_FINISH
}

CHOICES_PAPER_STATUS = (
    (FW_PAPER_STATUS_INIT, u'问卷录入中'),
    (FW_PAPER_STATUS_WAIT_AUDIT_1, u'等待QC一审'),
    (FW_PAPER_STATUS_WAIT_AUDIT_2, u'等待QC二审'),
    (FW_PAPER_STATUS_WAIT_AUDIT_3, u'等待QC三审'),
    (FW_PAPER_STATUS_WAIT_AUDIT_4, u'等待督导审核'),
    (FW_PAPER_STATUS_WAIT_AUDIT_5, u'等待研究审核'),
    (FW_PAPER_STATUS_WAIT_AUDIT_6, u'等待FW终审'),
    (FH_PAPER_STATUS_INPUT, u'复核团队数据录入中'),
    (FH_PAPER_STATUS_WAIT_AUDIT_1, u'等待复核团队审核'),
    (FH_PAPER_STATUS_WAIT_AUDIT_2, u'等待复核团队终审'),
    (PAPER_STATUS_FINISH, u'访问和审核已完成'),
)

ABSOLUTELY_MATCH = 2
HAS_CONFLICT = 3
FIXED_CONFLICT = 4

CHOICES_DIFF_STATUS = (
   (ABSOLUTELY_MATCH, u'无差异'),
   (HAS_CONFLICT, u'有差异'),
   (FIXED_CONFLICT, u'差异解决'),
)
FW_PAPER_TYPE = 'GFK'
FH_PAPER_TYPE = 'FHT'
BMW_PAPER_TYPE = 'BMW' #问卷得分最终使用此条记录
CHOICES_PAPER_TYPE = (
    (FW_PAPER_TYPE, u'FW问卷'),
    (FH_PAPER_TYPE, u'独立复核问卷'),
    (BMW_PAPER_TYPE, u'BMW最终问卷')
)

AUDIT_PAPER_STATUS = (
    (FW_PAPER_STATUS_INIT, u'在线数据录入'),
    (FW_PAPER_STATUS_WAIT_AUDIT_2, u'QC一审'),
    (FW_PAPER_STATUS_WAIT_AUDIT_3, u'QC二审'),
    (FW_PAPER_STATUS_WAIT_AUDIT_4, u'QC三审'),
    (FW_PAPER_STATUS_WAIT_AUDIT_5, u'督导审核'),
    (FW_PAPER_STATUS_WAIT_AUDIT_6, u'研究审核'),
    
    (FH_PAPER_STATUS_INPUT, u'复核团队数据录入中'),
    (FH_PAPER_STATUS_WAIT_AUDIT_1, u'等待复核团队审核'),
    (PAPER_STATUS_FINISH, u'终审'),
)

DEALER_REPORT_STATUS_NOTVISIT = 0
DEALER_REPORT_STATUS_NOTREADY = 1
DEALER_REPORT_STATUS_READY = 2

CHOICES_DEALER_REPORT_STATUS = (
    (DEALER_REPORT_STATUS_NOTVISIT, u'未执行访问'),
    (DEALER_REPORT_STATUS_NOTREADY, u'报告未生成'),
    (DEALER_REPORT_STATUS_READY, u'报告已生成'),
)

AREA_ALL = 1
AREA_NORTH = 2
AREA_SOUTH = 3
AREA_EAST = 4
AREA_WEST = 5

CHOICES_AREA_TYPE = (
    (AREA_ALL, u'全国'),
    (AREA_NORTH, u'北部区域'),
    (AREA_SOUTH, u'南部区域'),
    (AREA_EAST, u'东部区域'),
    (AREA_WEST, u'西部区域'),
)
