#encoding:utf-8

#encoding:utf-8


QUESTION_TYPE_SINGLE = 2
QUESTION_TYPE_MULTIPLE = 3
QUESTION_TYPE_MATRIX_SINGLE = 4
#QUESTION_TYPE_MATRIX_MULTIPLE = 5
QUESTION_TYPE_BLANK = 6
QUESTION_TYPE_MATRIX_SCORE = 7

QUESTION_TYPE_SCORE = 50
QUESTION_TYPE_MULTIPLE_SCORE = 51
QUESTION_TYPE_ORDER = 60
QUESTION_TYPE_DESC = 70
QUESTION_TYPE_MULTIPLE_BLANK = 95
QUESTION_TYPE_MATRIX_BLANK = 100
QUESTION_TYPE_MATRIX_BLANK_SCORE = 105
QUESTION_TYPE_VARIABLE = 8

CHOICES_QUESTION_TYPE = [
    (QUESTION_TYPE_SINGLE, u'单选题'),
    (QUESTION_TYPE_MULTIPLE, u'多选题'),
    (QUESTION_TYPE_BLANK, u'填空题'),
    #~ (QUESTION_TYPE_MULTIPLE_BLANK, u'多项填空题'),
    #~ (QUESTION_TYPE_MULTIPLE_SCORE, u'多项打分题'),
    (QUESTION_TYPE_SCORE, u'打分题'),
    (QUESTION_TYPE_MATRIX_SINGLE, u'矩阵单选题'),
    #~ (QUESTION_TYPE_MATRIX_MULTIPLE,u'矩阵多选题'),
    #~ (QUESTION_TYPE_MATRIX_SCORE,u'矩阵打分题'),   
    #~ (QUESTION_TYPE_MATRIX_BLANK, u'矩阵填空'),
    #~ (QUESTION_TYPE_MATRIX_BLANK_SCORE,u'矩阵填空打分题'),
    (QUESTION_TYPE_ORDER, u'排序题'),
    (QUESTION_TYPE_DESC, u'描述题'),
    (QUESTION_TYPE_VARIABLE, u"不定项选择题"),
]

RESPONDENT_STATUS_UNCOMPLETE = 0
RESPONDENT_STATUS_COMPLETE = 1
RESPONDENT_STATUS_SCREENOUT = 2
RESPONDENT_STATUS_QUOTAFULL = 3

CHOICES_RESPONDENT_STATUS = [
    (RESPONDENT_STATUS_UNCOMPLETE,u'未完成'),
    (RESPONDENT_STATUS_COMPLETE,u'已完成'),
    (RESPONDENT_STATUS_SCREENOUT,u'被删选'),
    (RESPONDENT_STATUS_QUOTAFULL,u'配额满'),
]


QUESTION_TYPE_DICT = dict(CHOICES_QUESTION_TYPE)
QTYPE_WITH_ALT_SET = set([
    QUESTION_TYPE_SINGLE,
    QUESTION_TYPE_MULTIPLE,
    QUESTION_TYPE_MATRIX_SINGLE,
    #~ QUESTION_TYPE_MATRIX_MULTIPLE,
    QUESTION_TYPE_SCORE,
    QUESTION_TYPE_MATRIX_SCORE,
    QUESTION_TYPE_ORDER,
    QUESTION_TYPE_VARIABLE,
    #~ QUESTION_TYPE_MULTIPLE_BLANK,
])

QTYPE_WITH_MATRIXROW_SET = set([
    QUESTION_TYPE_MATRIX_SINGLE,
    #~ QUESTION_TYPE_MATRIX_MULTIPLE,
    QUESTION_TYPE_MATRIX_SCORE,
])


CHECKPOINT_BASICTYPE_NODATE = 1
CHECKPOINT_BASICTYPE_DATE = 2
CHOICES_CHECKPOINT_DATETYPE = (
    (CHECKPOINT_BASICTYPE_NODATE, u'非日期填空题'),
    (CHECKPOINT_BASICTYPE_DATE, u'日期填空题'),
)

CHECKPOINT_TYPE_COUNT = 1
CHECKPOINT_TYPE_NOCOUNT = 2
CHOICES_CHECKPOINT_TYPE = (
    (CHECKPOINT_TYPE_COUNT, u'计分题'),
    (CHECKPOINT_TYPE_NOCOUNT, u'观察题'),
)

QUESTION_SHOW_TYPE_RADIO = 1
QUESTION_SHOW_TYPE_SELECT = 2

CHOICES_QUESTION_SHOW_TYPE = (
    (QUESTION_SHOW_TYPE_RADIO, u'单选框'),
    (QUESTION_SHOW_TYPE_SELECT, u'下拉框'),
)

QUESTIONNAIRE_SCORE_TYPE_WEIGHT = 1
QUESTIONNAIRE_SCORE_TYPE_PERCENT = 2
CHOICES_SCORE_TYPE = (
    (QUESTIONNAIRE_SCORE_TYPE_WEIGHT, u'统计权重'),
    (QUESTIONNAIRE_SCORE_TYPE_PERCENT, u'统计百分比')
)

SCORE_TYPE_NORMAL = 'normal'
SCORE_TYPE_YTD = 'YTD'
SCORE_TYPE_DEALERS = 'dealers'
CHOICES_SCORE_TYPES = [
    (SCORE_TYPE_NORMAL, u'常规'),
    (SCORE_TYPE_YTD, u'YTD'),
    (SCORE_TYPE_DEALERS, u'客户名单统计'),
]
  
